version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=swift_transfer
    ports:
      - "5432:5432"
    networks:
      - swift_network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/swift_transfer?sslmode=disable
    networks:
      - swift_network
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "5432","--" ]
    command: [ "/app/start.sh", "/app/main"]

networks:
  swift_network: