version: '3.8'
services:
  postgres-master:
    image: postgres:12
    container_name: postgres-master
    networks:
      - pg-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./master_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  postgres-replica:
    image: postgres:12
    container_name: postgres-replica
    networks:
      - pg-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./replica_data:/var/lib/postgresql/data
    depends_on:
      - postgres-master
    restart: always

networks:
  pg-network:
    driver: bridge
